// Libellés d'interface partagés (§14.8). Français uniquement.

export const labels = {
  app: {
    name: 'Sama3',
  },
  common: {
    loading: 'Chargement…',
  },
  record: {
    start: 'Commencer',
    stop: 'Arrêter',
    saving: 'Enregistrement…',
    meter: 'Niveau du son capté',
    hintIdle: 'Touchez avant la prière. L’écran restera allumé : posez le téléphone écran vers le sol, sans le verrouiller.',
    hintRecording: 'Ne verrouillez pas le téléphone. Touchez à la fin de la prière.',
    hintSaving: 'Mise de côté de l’enregistrement…',
    savedTitle: 'Enregistrement conservé',
    savedMessage: 'Il sera traité dès que le réseau sera disponible.',
    interruptedTitle: 'Enregistrement interrompu',
    interruptedMessage: 'Le téléphone a coupé le micro. L’audio déjà capturé est conservé et sera traité.',
  },
  recorderErrors: {
    'mic-denied': {
      title: 'Micro refusé',
      message: 'Autorisez l’accès au micro pour ce site dans les réglages du navigateur, puis réessayez.',
    },
    'mic-missing': {
      title: 'Aucun micro détecté',
      message: 'Branchez ou activez un micro, puis réessayez.',
    },
    unsupported: {
      title: 'Enregistrement impossible',
      message: 'Ce navigateur ne permet pas d’enregistrer l’audio. Essayez Safari ou Chrome à jour.',
    },
    'mic-failed': {
      title: 'Le micro n’a pas démarré',
      message: 'Une autre application l’utilise peut-être. Fermez-la et réessayez.',
    },
    empty: {
      title: 'Aucun son capturé',
      message: 'L’enregistrement est vide, il n’a pas été conservé.',
    },
    'save-failed': {
      title: 'Sauvegarde impossible',
      message: 'L’enregistrement n’a pas pu être écrit sur le téléphone (espace plein ?).',
    },
  },
  dismiss: 'Fermer',
  session: {
    defaultLabel: 'Prière',
  },
  queue: {
    title: 'En attente de traitement',
    pending: 'En attente',
    processing: 'Analyse en cours',
    error: 'Erreur',
    retry: 'Réessayer',
    offlineTitle: 'Hors ligne',
    offlineMessage: 'Les enregistrements seront analysés au retour du réseau.',
  },
  result: {
    back: 'Retour',
    passages: (n) => (n > 1 ? `${n} passages` : n === 1 ? '1 passage' : 'Aucun passage'),
    surah: (n) => `Sourate ${n}`,
    verses: (range) => `Versets ${range}`,
    verse: (n) => `Verset ${n}`,
    notFoundTitle: 'Prière introuvable',
    notFoundMessage: 'Cette prière n’existe plus dans l’historique.',
    emptyTitle: 'Aucun passage reconnu',
    emptyMessage: 'La récitation n’a pas pu être rapprochée du Coran (bruit, écho ou enregistrement trop court).',
    loadFailedTitle: 'Texte coranique indisponible',
    loadFailedMessage: 'Reconnectez-vous pour charger le texte, puis rouvrez cette prière.',
    translationMissing: 'Traduction indisponible hors ligne.',
    tabs: { arabic: 'Arabe', translation: 'Traduction', tafsir: 'Tafsir' },
    tafsirMissing: 'Tafsir indisponible hors ligne.',
    translationSource: 'Traduction : Rachid Maach',
    tafsirSource: 'Tafsir : L’Exégèse abrégée du Noble Coran',
  },
  nav: {
    label: 'Navigation',
    record: 'Enregistrer',
    history: 'Historique',
  },
  privacy: {
    title: 'Avant d’enregistrer',
    message: 'Demandez à la mosquée si l’enregistrement est autorisé. L’audio reste sur votre téléphone, n’est envoyé que pour la transcription, puis est supprimé.',
    ok: 'J’ai compris',
  },
  history: {
    title: 'Historique',
    export: 'Exporter',
    import: 'Importer',
    open: 'Ouvrir',
    rename: 'Renommer',
    delete: 'Supprimer',
    renamePrompt: 'Nom de la prière (Fajr, Dhuhr, Asr, Maghrib, Isha, Jumu’a, Tarawih…)',
    deleteConfirm: (label) => `Supprimer « ${label} » de l’historique ?`,
    emptyTitle: 'Aucune prière pour l’instant',
    emptyMessage: 'Les prières analysées apparaîtront ici.',
    emptyAction: 'Enregistrer une prière',
    imported: (n) => (n > 1 ? `${n} prières importées.` : n === 1 ? '1 prière importée.' : 'Aucune nouvelle prière à importer.'),
    importFailed: 'Ce fichier n’est pas un export Sama3 valide.',
    exportFileName: (date) => `sama3-historique-${date}.json`,
  },
  queueErrors: {
    'not-configured': 'Le service de transcription n’est pas encore configuré.',
    'too-large': 'Enregistrement trop volumineux pour être analysé.',
    timeout: 'Le service a mis trop de temps à répondre.',
    quota: 'Limite gratuite du jour atteinte. Réessayez plus tard.',
    http: 'Le service de transcription a renvoyé une erreur.',
    invalid: 'Réponse inattendue du service de transcription.',
    unknown: 'Une erreur inattendue est survenue.',
  },
};
